import {
  BuilderMember,
  EventSession,
  CertificateRecord,
  LearningResource,
  BlogPost,
  OpportunityItem,
  AnnouncementItem,
} from './types';

export const FOUNDER_DATA: BuilderMember = {
  id: 'disha-pure',
  name: 'Disha Pure',
  role: 'Founder & President',
  division: 'B.Tech CSIT (Cybersecurity) · Class of 2026',
  year: 'Batch of 2026',
  avatar: '/disha-pure.png',
  builderId: 'disha-pure-sspu',
  badges: ['AWS Student Captain', 'AWS Community Builder', 'Cybersecurity Lead', 'SSPU Chapter Lead'],
  certs: ['AWS Certified Solutions Architect – Associate Candidate', 'AWS Certified Cloud Practitioner'],
  bio: 'AWS Student Builder Group Leader and AWS Student Captain at SSPU. Specializing in Cybersecurity (CSIT ’26), she spearheads the "AWS Student Builder 101" initiative and hands-on cloud sprints in Lab 3, empowering students with production cloud architecture and security fundamentals.',
  github: 'https://github.com/dishapure',
  linkedin: 'https://www.linkedin.com/in/disha-pure-96b43b354/?isSelfProfile=false',
  portfolio: 'https://dishapure.dev',
  isLead: true,
  featured: true,
};

export const CORE_TEAM: BuilderMember[] = [
  FOUNDER_DATA,
  {
    id: 'aarav-sharma',
    name: 'Aarav Sharma',
    role: 'Cloud Architecture Lead',
    division: 'B.Tech CSIT · Class of 2026',
    year: 'Year 3',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600',
    builderId: 'aarav-sharma-sspu',
    badges: ['Serverless Hero', 'Terraform Specialist'],
    certs: ['AWS Solutions Architect Associate'],
    bio: 'Directs weekly architecture peer groups on VPC peering, multi-region routing, and serverless architectures.',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    isLead: true,
  },
  {
    id: 'ananya-deshmukh',
    name: 'Ananya Deshmukh',
    role: 'Cybersecurity Lead',
    division: 'B.Tech Cybersecurity · Class of 2026',
    year: 'Year 3',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=600',
    builderId: 'ananya-deshmukh-sspu',
    badges: ['Event Host', 'Security Scout'],
    certs: ['AWS Certified Security – Specialty Candidate'],
    bio: 'Conducts honeypot analysis labs, IAM zero-trust workshops, and automated threat detection on AWS.',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    isLead: true,
  },
  {
    id: 'rohan-kulkarni',
    name: 'Rohan Kulkarni',
    role: 'DevOps Lead',
    division: 'B.Tech CSIT · Class of 2026',
    year: 'Year 3',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600',
    builderId: 'rohan-kulkarni-sspu',
    badges: ['Kubernetes Ninja', 'CI/CD Master'],
    certs: ['AWS Certified SysOps Administrator'],
    bio: 'Automates our CI/CD pipelines, manages sandbox AWS accounts, and mentors students on AWS CDK and Terraform.',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    isLead: true,
  },
  {
    id: 'priya-nair',
    name: 'Priya Nair',
    role: 'GenAI & ML Initiatives Lead',
    division: 'B.Tech Data Science & AI',
    year: 'Year 3',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600',
    badges: ['Bedrock Pioneer', 'LangChain Expert'],
    certs: ['AWS Certified Machine Learning – Specialty'],
    bio: 'Curates hands-on Amazon Bedrock, SageMaker JumpStart, and RAG architectures for collegiate workshops.',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    isLead: false,
  },
  {
    id: 'aditya-joshi',
    name: 'Aditya Joshi',
    role: 'Community Evangelist & Outreach',
    division: 'B.Tech CSIT',
    year: 'Year 2',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600',
    badges: ['Speaker', 'Content Lead'],
    certs: ['AWS Certified Cloud Practitioner'],
    bio: 'Drives inter-college hackathons, newsletter dispatches, and student onboarding mentorship.',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    isLead: false,
  },
];

export const UPCOMING_EVENTS: EventSession[] = [
  {
    id: 'evt-reinvent-bedrock',
    title: 're:Invent Watch Party & Bedrock GenAI Sprint',
    type: 'Watch Party',
    date: 'Saturday, 10:00 AM IST',
    time: '10:00 AM – 01:00 PM IST',
    location: 'Computer Lab 3, Academic Block, SSPU Kiwale Campus',
    speaker: 'Disha Pure & AWS Community Mentors',
    speakerRole: 'Founder & Solutions Architects',
    tags: ['re:Invent', 'Amazon Bedrock', 'Lab 3'],
    seatsRemaining: 18,
    totalSeats: 60,
    description: 'Live streaming keynote announcements followed by a 2-hour hands-on Claude 3.5 Sonnet serverless sprint on Amazon Bedrock in Computer Lab 3.',
    isPast: false,
  },
  {
    id: 'evt-saa-c03-cohort',
    title: 'Solutions Architect Associate (SAA-C03) Study Cohort',
    type: 'Workshop',
    date: 'Wednesday, 04:30 PM IST',
    time: '04:30 PM – 06:30 PM IST',
    location: 'Computer Lab 3, Academic Block, SSPU Kiwale Campus',
    speaker: 'Disha Pure & Aarav Sharma',
    speakerRole: 'AWS Certified Architects',
    tags: ['SAA-C03', 'Cloud Architecture'],
    seatsRemaining: 24,
    totalSeats: 50,
    description: 'Weekly peer reviews covering VPC peering, IAM zero-trust boundaries, Aurora clustering, and architectural case studies.',
    isPast: false,
  },
  {
    id: 'evt-cloud-security-honeypot',
    title: 'Cloud Security & AI Honeypot Defense Lab',
    type: 'Bootcamp',
    date: 'Saturday, 02:00 PM IST',
    time: '02:00 PM – 05:30 PM IST',
    location: 'Computer Lab 3, Academic Block, SSPU Kiwale Campus',
    speaker: 'Ananya Deshmukh & Cybersecurity SIG Leads',
    speakerRole: 'Security Special Interest Group',
    tags: ['Security', 'AWS WAF', 'Python'],
    seatsRemaining: 12,
    totalSeats: 45,
    description: 'Hands-on analysis of EC2 honeypot logs, AWS WAF rules, and automated threat classification with Python.',
    isPast: false,
  },
];

export const PAST_EVENTS: EventSession[] = [
  {
    id: 'evt-past-serverless-lambda',
    title: 'Zero to Serverless: Microservices with AWS Lambda & DynamoDB',
    type: 'Workshop',
    date: 'SEP 14, 2026',
    time: '02:00 PM – 05:30 PM IST',
    location: 'Computer Lab 3, SSPU Kiwale Campus',
    speaker: 'Disha Pure',
    speakerRole: 'Community Lead',
    tags: ['AWS Lambda', 'DynamoDB', 'SAM'],
    seatsRemaining: 0,
    totalSeats: 60,
    description: 'Architected and deployed a production REST microservice backed by AWS Lambda and single-table DynamoDB.',
    isPast: true,
    attendedCount: 58,
    slidesUrl: 'https://sbg-sspu.org/decks/serverless-microservices-101.pdf',
    githubUrl: 'https://github.com/aws-sbg-sspu/serverless-microservices',
  },
  {
    id: 'evt-past-bedrock-rag',
    title: 'GenAI RAG Architecture with Amazon Bedrock & OpenSearch',
    type: 'Bootcamp',
    date: 'AUG 28, 2026',
    time: '11:00 AM – 03:00 PM IST',
    location: 'Computer Lab 3, SSPU Kiwale Campus',
    speaker: 'Priya Nair & Disha Pure',
    speakerRole: 'GenAI Cohort Leads',
    tags: ['Bedrock', 'Vector Search', 'RAG'],
    seatsRemaining: 0,
    totalSeats: 50,
    description: 'Constructed an end-to-end vector knowledge base pipeline indexing SSPU curriculum documents.',
    isPast: true,
    attendedCount: 47,
    slidesUrl: 'https://sbg-sspu.org/decks/bedrock-rag-pipeline.pdf',
    githubUrl: 'https://github.com/aws-sbg-sspu/bedrock-rag-pipeline',
  },
  {
    id: 'evt-past-season-kickoff',
    title: 'AWS SBG @ SSPU Season Launch & Cloud Career Roadmap',
    type: 'Keynote',
    date: 'AUG 08, 2026',
    time: '04:00 PM – 06:00 PM IST',
    location: 'Computer Lab 3 & Auditorium',
    speaker: 'Disha Pure & Faculty Advisory Board',
    speakerRole: 'AWS SBG Core',
    tags: ['Roadmap', 'Community'],
    seatsRemaining: 0,
    totalSeats: 120,
    description: 'Inaugural chapter assembly introducing student cloud sandboxes, Lab 3 schedules, and certification paths.',
    isPast: true,
    attendedCount: 114,
    slidesUrl: 'https://sbg-sspu.org/decks/sbg-launch-roadmap.pdf',
    githubUrl: 'https://github.com/aws-sbg-sspu/cloud-starter-kit',
  },
];

export const MOCK_CERTIFICATES: CertificateRecord[] = [
  {
    id: 'CERT-SSPU-2026-001',
    recipientName: 'Disha Pure',
    prn: '20220104001',
    eventName: 'AWS Student Builder Group Founding Chair',
    date: '2026-08-01',
    issueId: 'AWS-SBG-SSPU-FOUNDER-01',
    verificationUrl: 'https://verify.sbg-sspu.org/cert/001',
    credentialTier: 'Gold Builder',
    skillsVerified: ['Cloud Architecture', 'Community Leadership', 're:Invent Coordination', 'AWS Well-Architected'],
  },
  {
    id: 'CERT-SSPU-2026-042',
    recipientName: 'Aarav Sharma',
    prn: '20220104042',
    eventName: 'Zero to Serverless Microservices Workshop',
    date: '2026-09-14',
    issueId: 'AWS-SBG-SSPU-WS-9482',
    verificationUrl: 'https://verify.sbg-sspu.org/cert/042',
    credentialTier: 'Gold Builder',
    skillsVerified: ['AWS Lambda', 'DynamoDB NoSQL', 'API Gateway', 'AWS SAM'],
  },
  {
    id: 'CERT-SSPU-2026-088',
    recipientName: 'Rohan Kulkarni',
    prn: '20230104088',
    eventName: 'DevOps & GitOps Pipeline Intensive',
    date: '2026-09-21',
    issueId: 'AWS-SBG-SSPU-WS-7319',
    verificationUrl: 'https://verify.sbg-sspu.org/cert/088',
    credentialTier: 'Silver Builder',
    skillsVerified: ['CodePipeline', 'CloudFormation', 'Docker on ECS', 'IAM Least Privilege'],
  },
  {
    id: 'CERT-SSPU-2026-114',
    recipientName: 'Ananya Deshmukh',
    prn: '20220104114',
    eventName: 'AWS Cloud Security & Governance Sprint',
    date: '2026-09-28',
    issueId: 'AWS-SBG-SSPU-WS-6621',
    verificationUrl: 'https://verify.sbg-sspu.org/cert/114',
    credentialTier: 'Gold Builder',
    skillsVerified: ['AWS KMS', 'GuardDuty', 'Security Hub', 'IAM Policies'],
  },
];

export const LEARNING_PATHS: LearningResource[] = [
  {
    id: 'lp-architect',
    title: 'Solutions Architect Fast-Track',
    level: 'Associate',
    category: 'Cloud Architecture',
    duration: '6 Weeks (Self-paced + Labs)',
    description: 'Master VPC subnets, transit gateways, auto-scaling groups, ALB routing, S3 storage tiers, and RDS Aurora multi-region setups.',
    iconName: 'Layers',
    url: '#',
    modulesCount: 18,
  },
  {
    id: 'lp-genai',
    title: 'Generative AI with Amazon Bedrock & SageMaker',
    level: 'Specialty',
    category: 'Machine Learning',
    duration: '4 Weeks',
    description: 'Build RAG pipelines, fine-tune models, implement guardrails, and build generative search engines with Claude 3.5 on AWS.',
    iconName: 'Cpu',
    url: '#',
    modulesCount: 12,
  },
  {
    id: 'lp-devops',
    title: 'Serverless DevOps & Infrastructure as Code',
    level: 'Associate',
    category: 'DevOps & CI/CD',
    duration: '5 Weeks',
    description: 'Automate deployments with AWS CDK, Terraform, GitHub Actions, CloudWatch alarms, and AWS Lambda telemetry.',
    iconName: 'Terminal',
    url: '#',
    modulesCount: 15,
  },
  {
    id: 'lp-security',
    title: 'Cloud Security, IAM & Zero-Trust Governance',
    level: 'Professional',
    category: 'Security',
    duration: '4 Weeks',
    description: 'Deep dive into SCPs, Control Tower, GuardDuty anomaly detection, KMS envelope encryption, and SOC2 compliance automation.',
    iconName: 'ShieldCheck',
    url: '#',
    modulesCount: 10,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'Architecting for 99.99% Availability: Lessons from the SSPU Hackathon Portal',
    author: 'Disha Pure',
    authorRole: 'Founder & Community Lead',
    date: 'OCT 01, 2026',
    readTime: '6 min read',
    excerpt: 'How we configured Amazon CloudFront, Route 53 latency-based routing, and Aurora Serverless v2 to withstand 15,000 concurrent student requests without crashing.',
    tags: ['Architecture', 'CloudFront', 'Aurora Serverless'],
    coverColor: 'from-purple-900/60 to-slate-900',
    likes: 48,
  },
  {
    id: 'blog-2',
    title: 'Demystifying Amazon Bedrock: Connecting Claude 3.5 Sonnet to Student Resumes',
    author: 'Priya Nair',
    authorRole: 'GenAI Lead',
    date: 'SEP 26, 2026',
    readTime: '8 min read',
    excerpt: 'A complete step-by-step walkthrough of building a conversational HR screener using OpenSearch Serverless vector embeddings and Bedrock Anthropic APIs.',
    tags: ['Amazon Bedrock', 'GenAI', 'Vector Search'],
    coverColor: 'from-amber-900/60 to-slate-900',
    likes: 62,
  },
  {
    id: 'blog-3',
    title: 'Why Every Engineering Undergrad at SSPU Should Clear AWS SAA-C03 by Year 3',
    author: 'Aarav Sharma',
    authorRole: 'Technical Lead',
    date: 'SEP 19, 2026',
    readTime: '5 min read',
    excerpt: 'Breaking down the placement ROI, real architectural problem solving, and portfolio credibility of obtaining an AWS associate certification early in college.',
    tags: ['Careers', 'Certifications', 'Student Advice'],
    coverColor: 'from-blue-900/60 to-slate-900',
    likes: 89,
  },
];

export const OPPORTUNITIES: OpportunityItem[] = [
  {
    id: 'opp-1',
    title: 'AWS Cloud Support Associate (Graduate Program)',
    company: 'Amazon Web Services (AWS)',
    type: 'Full-Time',
    location: 'Pune / Hyderabad, India',
    deadline: 'NOV 15, 2026',
    link: 'https://amazon.jobs',
    tags: ['Networking', 'Linux', 'AWS Core Services'],
    isVerified: true,
  },
  {
    id: 'opp-2',
    title: 'DevOps & Cloud Engineer Intern',
    company: 'Persistent Systems',
    type: 'Internship',
    location: 'Hinjawadi, Pune',
    stipend: '₹35,000 / month',
    deadline: 'OCT 30, 2026',
    link: '#',
    tags: ['Docker', 'AWS ECS', 'Terraform', 'CI/CD'],
    isVerified: true,
  },
  {
    id: 'opp-3',
    title: 'AWS GenAI Builder Grant 2026-27',
    company: 'AWS Community Fellowship',
    type: 'Hackathon Grant',
    location: 'Remote / Virtual',
    stipend: '$2,000 AWS Promotional Credits',
    deadline: 'DEC 01, 2026',
    link: '#',
    tags: ['Amazon Bedrock', 'SageMaker', 'Open Source'],
    isVerified: true,
  },
];

export const ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'anc-1',
    title: 'AWS re:Invent Watch Party Registration is Now Live for SSPU Students',
    date: 'OCT 01, 2026',
    priority: 'CRITICAL',
    category: 'Event Alert',
    content: 'Seats for Auditorium A are limited to 120 students on a first-come, first-served basis. Every attendee gets an official AWS swags bundle, sticker sheet, and attendance certificate.',
    author: 'Disha Pure, Founder',
  },
  {
    id: 'anc-2',
    title: 'AWS Certification Exam Voucher Reimbursement Initiative Announced',
    date: 'SEP 25, 2026',
    priority: 'UPDATE',
    category: 'Academic Perk',
    content: 'Students who clear the AWS Solutions Architect Associate or Cloud Practitioner exam during this semester are eligible for up to 50% fee reimbursement via the university innovation fund.',
    author: 'SSPU Faculty Advisory',
  },
  {
    id: 'anc-3',
    title: 'Official SBG GitHub Organization Open for Open-Source Contributors',
    date: 'SEP 18, 2026',
    priority: 'NORMAL',
    category: 'Codebase',
    content: 'Check out our repository for the Student Builder Pass verification microservice and contribute PRs to earn the Silver Builder badge.',
    author: 'Aarav Sharma, Technical Lead',
  },
];
